import os
from aery_plugin.logger import logger

def export_as_processing_macro(name: str, code: str) -> bool:
    """Wrap agent code in a QGIS Processing Script and save it to the user's profile."""
    try:
        from qgis.core import QgsApplication
        # QGIS profile directory path
        profile_path = QgsApplication.qgisSettingsDirPath()
        scripts_dir = os.path.join(profile_path, "processing", "scripts")
        os.makedirs(scripts_dir, exist_ok=True)
        
        # Format the class name
        class_name = "".join(x.capitalize() for x in name.replace("-", "_").split("_")) + "Algorithm"
        safe_name = name.lower().replace(" ", "_").replace("-", "_")
        
        # Extract imports from the agent's code to place at the top of the script
        import_lines = []
        body_lines = []
        for line in code.split("\n"):
            if line.startswith("import ") or line.startswith("from "):
                import_lines.append(line)
            else:
                body_lines.append(line)
                
        # Deduplicate imports
        import_lines = list(dict.fromkeys(import_lines))
        imports_str = "\n".join(import_lines)
        
        # Indent body
        body_indented = "\n        ".join(body_lines)
        if not body_indented.strip():
            body_indented = "pass"
            
        # The QGIS Processing Template
        template = f'''"""
Model exported by Aery AI
"""
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingException,
                       QgsProject)
{imports_str}

class {class_name}(QgsProcessingAlgorithm):
    """
    {name}
    """

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return {class_name}()

    def name(self):
        return '{safe_name}'

    def displayName(self):
        return self.tr('{name}')

    def group(self):
        return self.tr('Aery Macros')

    def groupId(self):
        return 'aery_macros'

    def shortHelpString(self):
        return self.tr("Macro generated by Aery AI.")

    def initAlgorithm(self, config=None):
        pass

    def processAlgorithm(self, parameters, context, feedback):
        feedback.pushInfo("Running Aery Macro: {name}")
        
        # Execute the AI's code
        {body_indented}
        
        return {{}}
'''
        file_path = os.path.join(scripts_dir, f"{safe_name}.py")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(template)
            
        logger.info(f"Saved Macro to: {file_path}")
        
        # Try to reload the processing registry if possible
        try:
            import processing
            from processing.core.Processing import Processing
            # Refresh the algorithm provider
            provider = processing.core.Processing.Processing.algs.getProviderFromName("script")
            if provider:
                provider.refreshAlgorithms()
        except Exception as e:
            logger.warning(f"Could not automatically refresh Processing Toolbox: {e}")
            
        return True
    except Exception as e:
        logger.error(f"Failed to export macro: {e}")
        return False
