"""Complete Aery provider registry."""
from typing import Any, Optional
class Model:
    def __init__(self, id: str, name: str, api: str, provider: str, base_url: str, max_tokens: Optional[int] = None):
        self.id = id
        self.name = name
        self.api = api
        self.provider = provider
        self.base_url = base_url
        # Derive a sensible max output token budget from the model id family
        # when the registry does not specify one explicitly. Avoids a flat
        # 8192 default for models that support 64k+ outputs.
        self.max_tokens = max_tokens if max_tokens else _default_max_tokens(id)
def _default_max_tokens(model_id: str) -> int:
    """Heuristic output-token budget by model family."""
    mid = model_id.lower()
    if "gemini" in mid:
        if "pro" in mid:
            return 65536
        return 8192
    if "gpt-5" in mid or "gpt5" in mid or mid.startswith("gpt-5"):
        return 32768
    if "claude" in mid or "sonnet" in mid or "opus" in mid or "haiku" in mid:
        return 8192
    if "deepseek" in mid or "llama" in mid or "qwen" in mid or "glm" in mid:
        return 8192
    return 8192  # safe default
PROVIDERS: dict[str, dict[str, Model]] = {}
def _add(provider_id: str, model_id: str, **kwargs) -> None:
    if provider_id not in PROVIDERS:
        PROVIDERS[provider_id] = {}
    PROVIDERS[provider_id][model_id] = Model(id=model_id, provider=provider_id, **kwargs)
# google-antigravity
_add("google-antigravity", "claude-opus-4-5-thinking", name="Claude Opus 4.5 Thinking (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "claude-opus-4-6-thinking", name="Claude Opus 4.6 (Thinking) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "claude-sonnet-4-5", name="Claude Sonnet 4.5", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "claude-sonnet-4-5-thinking", name="Claude Sonnet 4.5 Thinking (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "claude-sonnet-4-6", name="Claude Sonnet 4.6", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "claude-sonnet-4-6-thinking", name="Claude Sonnet 4.6 Thinking (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-2.5-flash", name="Gemini 2.5 Flash", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-2.5-flash-thinking", name="Gemini 2.5 Flash (Thinking) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-2.5-pro", name="Gemini 2.5 Pro", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-3-flash", name="Gemini 3 Flash", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-3-pro-high", name="Gemini 3 Pro (High) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-3-pro-low", name="Gemini 3 Pro (Low) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-3.1-pro-high", name="Gemini 3.1 Pro (High) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gemini-3.1-pro-low", name="Gemini 3.1 Pro (Low) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
_add("google-antigravity", "gpt-oss-120b-medium", name="GPT-OSS 120B (Medium) (Antigravity)", api="google-gemini-cli", base_url="https://daily-cloudcode-pa.sandbox.googleapis.com")
# kilo
_add("kilo", "~anthropic/claude-haiku-latest", name="Anthropic Claude Haiku Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~anthropic/claude-opus-latest", name="Anthropic: Claude Opus Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~anthropic/claude-sonnet-latest", name="Anthropic Claude Sonnet Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~google/gemini-flash-latest", name="Google Gemini Flash Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~google/gemini-pro-latest", name="Google Gemini Pro Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~moonshotai/kimi-latest", name="MoonshotAI Kimi Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~openai/gpt-latest", name="OpenAI GPT Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "~openai/gpt-mini-latest", name="OpenAI GPT Mini Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "ai21/jamba-large-1.7", name="AI21: Jamba Large 1.7", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "aion-labs/aion-1.0", name="AionLabs: Aion-1.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "aion-labs/aion-1.0-mini", name="AionLabs: Aion-1.0-Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "aion-labs/aion-2.0", name="AionLabs: Aion-2.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "aion-labs/aion-rp-llama-3.1-8b", name="AionLabs: Aion-RP 1.0 (8B)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "alfredpros/codellama-7b-instruct-solidity", name="AlfredPros: CodeLLaMa 7B Instruct Solidity", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "alibaba/tongyi-deepresearch-30b-a3b", name="Tongyi DeepResearch 30B A3B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/molmo-2-8b", name="AllenAI: Molmo2 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-2-0325-32b-instruct", name="AllenAI: Olmo 2 32B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-3-32b-think", name="AllenAI: Olmo 3 32B Think", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-3-7b-instruct", name="AllenAI: Olmo 3 7B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-3-7b-think", name="AllenAI: Olmo 3 7B Think", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-3.1-32b-instruct", name="AllenAI: Olmo 3.1 32B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "allenai/olmo-3.1-32b-think", name="AllenAI: Olmo 3.1 32B Think", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "alpindale/goliath-120b", name="Goliath 120B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "amazon/nova-2-lite-v1", name="Amazon: Nova 2 Lite", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "amazon/nova-lite-v1", name="Amazon: Nova Lite 1.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "amazon/nova-micro-v1", name="Amazon: Nova Micro 1.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "amazon/nova-premier-v1", name="Amazon: Nova Premier 1.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "amazon/nova-pro-v1", name="Amazon: Nova Pro 1.0", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthracite-org/magnum-v4-72b", name="Magnum v4 72B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-3-haiku", name="Claude Haiku 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-3.5-haiku", name="Claude 3.5 Haiku", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-3.5-sonnet", name="Claude Sonnet 3.5 v2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-3.7-sonnet", name="Claude 3.7 Sonnet", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-3.7-sonnet:thinking", name="Anthropic: Claude 3.7 Sonnet (thinking)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-haiku-4.5", name="Claude Haiku 4.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4", name="Claude Opus 4 (latest)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.1", name="Claude Opus 4.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.5", name="Claude Opus 4.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.6", name="Claude Opus 4.6", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.6-fast", name="Anthropic: Claude Opus 4.6 (Fast) ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.7", name="Claude Opus 4.7", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.7-fast", name="Anthropic: Claude Opus 4.7 (Fast) ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.8", name="Anthropic: Claude Opus 4.8 (new)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-opus-4.8-fast", name="Anthropic: Claude Opus 4.8 (Fast) ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-sonnet-4", name="Claude Sonnet 4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-sonnet-4.5", name="Claude Sonnet 4.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "anthropic/claude-sonnet-4.6", name="Claude Sonnet 4.6", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/coder-large", name="Arcee AI: Coder Large", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/maestro-reasoning", name="Arcee AI: Maestro Reasoning", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/spotlight", name="Arcee AI: Spotlight", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/trinity-large-preview", name="Arcee AI: Trinity Large Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/trinity-large-preview:free", name="Arcee AI: Trinity Large Preview (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/trinity-large-thinking", name="Arcee AI: Trinity Large Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/trinity-large-thinking:free", name="Arcee AI: Trinity Large Thinking (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/trinity-mini", name="Arcee AI: Trinity Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "arcee-ai/virtuoso-large", name="Arcee AI: Virtuoso Large", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/cobuddy:free", name="Baidu Qianfan: CoBuddy (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/ernie-4.5-21b-a3b", name="Baidu: ERNIE 4.5 21B A3B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/ernie-4.5-21b-a3b-thinking", name="Baidu: ERNIE 4.5 21B A3B Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/ernie-4.5-300b-a47b", name="Baidu: ERNIE 4.5 300B A47B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/ernie-4.5-vl-28b-a3b", name="Baidu: ERNIE 4.5 VL 28B A3B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/ernie-4.5-vl-424b-a47b", name="Baidu: ERNIE 4.5 VL 424B A47B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/qianfan-ocr-fast", name="Baidu: Qianfan-OCR-Fast", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "baidu/qianfan-ocr-fast:free", name="Baidu: Qianfan-OCR-Fast (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance-seed/dola-seed-2.0-pro:free", name="ByteDance Seed: Dola Seed 2.0 Pro (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance-seed/seed-1.6", name="ByteDance Seed: Seed 1.6", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance-seed/seed-1.6-flash", name="ByteDance Seed: Seed 1.6 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance-seed/seed-2.0-lite", name="ByteDance Seed: Seed-2.0-Lite", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance-seed/seed-2.0-mini", name="ByteDance Seed: Seed-2.0-Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "bytedance/ui-tars-1.5-7b", name="ByteDance: UI-TARS 7B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "cohere/command-a", name="Cohere: Command A", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "cohere/command-r-08-2024", name="Cohere: Command R (08-2024)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "cohere/command-r-plus-08-2024", name="Cohere: Command R+ (08-2024)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "cohere/command-r7b-12-2024", name="Cohere: Command R7B (12-2024)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "corethink:free", name="CoreThink (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepcogito/cogito-v2.1-671b", name="Deep Cogito: Cogito v2.1 671B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-chat", name="DeepSeek-V3.2 (Non-thinking Mode)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-chat-v3-0324", name="DeepSeek: DeepSeek V3 0324", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-chat-v3.1", name="DeepSeek: DeepSeek V3.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-r1", name="DeepSeek: R1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-r1-0528", name="DeepSeek: R1 0528", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-r1-distill-llama-70b", name="DeepSeek: R1 Distill Llama 70B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-r1-distill-qwen-32b", name="DeepSeek: R1 Distill Qwen 32B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v3.1-terminus", name="DeepSeek: DeepSeek V3.1 Terminus", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v3.1-terminus:exacto", name="DeepSeek: DeepSeek V3.1 Terminus (exacto)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v3.2", name="DeepSeek V3.2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v3.2-exp", name="DeepSeek-V3.2-Exp", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v3.2-speciale", name="DeepSeek: DeepSeek V3.2 Speciale", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v4-flash", name="DeepSeek V4 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v4-flash:discounted", name="DeepSeek: DeepSeek V4 Flash (>40% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v4-flash:free", name="DeepSeek: DeepSeek V4 Flash (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v4-pro", name="DeepSeek V4 Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "deepseek/deepseek-v4-pro:discounted", name="DeepSeek: DeepSeek V4 Pro (>80% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "eleutherai/llemma_7b", name="EleutherAI: Llemma 7b", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "essentialai/rnj-1-instruct", name="EssentialAI: Rnj 1 Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "giga-potato", name="Giga Potato (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "giga-potato-thinking", name="Giga Potato Thinking (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.0-flash-001", name="Google: Gemini 2.0 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.0-flash-lite-001", name="Google: Gemini 2.0 Flash Lite", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-flash", name="Gemini 2.5 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-flash-image", name="Google: Nano Banana (Gemini 2.5 Flash Image)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-flash-lite", name="Gemini 2.5 Flash Lite", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-flash-lite-preview-09-2025", name="Google: Gemini 2.5 Flash Lite Preview 09-2025", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-pro", name="Gemini 2.5 Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-pro-preview", name="Google: Gemini 2.5 Pro Preview 06-05", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-2.5-pro-preview-05-06", name="Google: Gemini 2.5 Pro Preview 05-06", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3-flash-preview", name="Gemini 3 Flash Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3-pro-image-preview", name="Google: Nano Banana Pro (Gemini 3 Pro Image Preview)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3-pro-preview", name="Gemini 3 Pro Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.1-flash-image-preview", name="Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.1-flash-lite", name="Google: Gemini 3.1 Flash Lite", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.1-flash-lite-preview", name="Gemini 3.1 Flash Lite Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.1-pro-preview", name="Gemini 3.1 Pro Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.1-pro-preview-customtools", name="Google: Gemini 3.1 Pro Preview Custom Tools", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemini-3.5-flash", name="Google: Gemini 3.5 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-2-27b-it", name="Google: Gemma 2 27B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-2-9b-it", name="Google: Gemma 2 9B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-3-12b-it", name="Google: Gemma 3 12B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-3-27b-it", name="Gemma-3-27B-IT", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-3-4b-it", name="Google: Gemma 3 4B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-3n-e4b-it", name="Gemma 3n E4b It", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-4-26b-a4b-it", name="Google: Gemma 4 26B A4B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/gemma-4-31b-it", name="Gemma-4-31B-IT", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/lyria-3-clip-preview", name="Google: Lyria 3 Clip Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "google/lyria-3-pro-preview", name="Google: Lyria 3 Pro Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "gryphe/mythomax-l2-13b", name="MythoMax 13B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "ibm-granite/granite-4.0-h-micro", name="IBM: Granite 4.0 Micro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "ibm-granite/granite-4.1-8b", name="IBM: Granite 4.1 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inception/mercury", name="Inception: Mercury", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inception/mercury-2", name="Inception: Mercury 2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inception/mercury-coder", name="Inception: Mercury Coder", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ling-2.6-1t", name="inclusionAI: Ling-2.6-1T", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ling-2.6-1t:free", name="inclusionAI: Ling-2.6-1T (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ling-2.6-flash", name="inclusionAI: Ling-2.6-flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ling-2.6-flash:free", name="inclusionAI: Ling-2.6-flash (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ring-2.6-1t", name="inclusionAI: Ring-2.6-1T", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inclusionai/ring-2.6-1t:free", name="inclusionAI: Ring-2.6-1T (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inflection/inflection-3-pi", name="Inflection: Inflection 3 Pi", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "inflection/inflection-3-productivity", name="Inflection: Inflection 3 Productivity", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo-auto/balanced", name="Auto Balanced", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo-auto/free", name="Auto Free", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo-auto/frontier", name="Auto Frontier", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo-auto/small", name="Auto Small", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo/auto", name="Deprecated Kilo Auto Frontier", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo/auto-free", name="Deprecated Kilo Auto Free", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kilo/auto-small", name="Deprecated Kilo Auto Small", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kwaipilot/kat-coder-pro", name="Kwaipilot: KAT-Coder-Pro V1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "kwaipilot/kat-coder-pro-v2", name="Kwaipilot: KAT-Coder-Pro V2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "liquid/lfm-2-24b-a2b", name="LiquidAI: LFM2-24B-A2B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "liquid/lfm-2.2-6b", name="LiquidAI: LFM2-2.6B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "liquid/lfm2-8b-a1b", name="LiquidAI: LFM2-8B-A1B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mancer/weaver", name="Mancer: Weaver (alpha)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meituan/longcat-flash-chat", name="Meituan: LongCat Flash Chat", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3-70b-instruct", name="Meta: Llama 3 70B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3-8b-instruct", name="Meta: Llama 3 8B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.1-405b", name="Meta: Llama 3.1 405B (base)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.1-405b-instruct", name="Meta: Llama 3.1 405B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.1-70b-instruct", name="Meta: Llama 3.1 70B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.1-8b-instruct", name="Meta: Llama 3.1 8B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.2-11b-vision-instruct", name="Meta: Llama 3.2 11B Vision Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.2-1b-instruct", name="Meta: Llama 3.2 1B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.2-3b-instruct", name="Meta: Llama 3.2 3B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-3.3-70b-instruct", name="Meta: Llama 3.3 70B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-4-maverick", name="Meta: Llama 4 Maverick", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-4-scout", name="Meta: Llama 4 Scout", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-guard-2-8b", name="Meta: LlamaGuard 2 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-guard-3-8b", name="Llama Guard 3 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-guard-4-12b", name="Meta: Llama Guard 4 12B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "meta-llama/llama-guard-4-12b:free", name="Meta: Llama Guard 4 12B (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "microsoft/phi-4", name="Microsoft: Phi 4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "microsoft/phi-4-mini-instruct", name="Phi-4-Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "microsoft/wizardlm-2-8x22b", name="WizardLM-2 8x22B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-01", name="MiniMax: MiniMax-01", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m1", name="MiniMax: MiniMax M1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2", name="MiniMax M2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2-her", name="MiniMax: MiniMax M2-her", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2.1", name="MiniMax M2.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2.5", name="MiniMax M2.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2.5:free", name="MiniMax: MiniMax M2.5 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m2.7", name="MiniMax M2.7", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "minimax/minimax-m3", name="MiniMax: MiniMax M3 (new)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/codestral-2508", name="Mistral: Codestral 2508", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/devstral-2512", name="Mistral: Devstral 2 2512", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/devstral-medium", name="Mistral: Devstral Medium", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/devstral-small", name="Mistral: Devstral Small 1.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/ministral-14b-2512", name="Mistral: Ministral 3 14B 2512", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/ministral-3b-2512", name="Mistral: Ministral 3 3B 2512", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/ministral-8b-2512", name="Mistral: Ministral 3 8B 2512", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-7b-instruct", name="Mistral: Mistral 7B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-7b-instruct-v0.1", name="Mistral: Mistral 7B Instruct v0.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-7b-instruct-v0.3", name="Mistral: Mistral 7B Instruct v0.3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-large", name="Mistral Large", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-large-2407", name="Mistral Large 2407", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-large-2411", name="Mistral Large 2411", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-large-2512", name="Mistral: Mistral Large 3 2512", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-medium-3", name="Mistral: Mistral Medium 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-medium-3-5", name="Mistral: Mistral Medium 3.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-medium-3.1", name="Mistral: Mistral Medium 3.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-nemo", name="Mistral: Mistral Nemo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-saba", name="Mistral: Saba", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-small-24b-instruct-2501", name="Mistral: Mistral Small 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-small-2603", name="Mistral: Mistral Small 4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-small-3.1-24b-instruct", name="Mistral: Mistral Small 3.1 24B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-small-3.2-24b-instruct", name="Mistral: Mistral Small 3.2 24B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mistral-small-creative", name="Mistral: Mistral Small Creative", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mixtral-8x22b-instruct", name="Mistral: Mixtral 8x22B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/mixtral-8x7b-instruct", name="Mistral: Mixtral 8x7B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/pixtral-large-2411", name="Mistral: Pixtral Large 2411", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "mistralai/voxtral-small-24b-2507", name="Mistral: Voxtral Small 24B 2507", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2", name="MoonshotAI: Kimi K2 0711", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2-0905", name="Kimi K2 0905", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2-0905:exacto", name="MoonshotAI: Kimi K2 0905 (exacto)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2-thinking", name="Kimi K2 Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2.5", name="Kimi K2.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2.5:free", name="MoonshotAI: Kimi K2.5 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2.6", name="Kimi K2.6", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "moonshotai/kimi-k2.6:free", name="MoonshotAI: Kimi K2.6 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "morph-warp-grep-v2", name="Morph: WarpGrep V2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "morph/morph-v3-fast", name="Morph: Morph V3 Fast", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "morph/morph-v3-large", name="Morph: Morph V3 Large", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "neversleep/llama-3.1-lumimaid-8b", name="NeverSleep: Lumimaid v0.2 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "neversleep/noromaid-20b", name="Noromaid 20B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nex-agi/deepseek-v3.1-nex-n1", name="Nex AGI: DeepSeek V3.1 Nex N1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nousresearch/hermes-2-pro-llama-3-8b", name="NousResearch: Hermes 2 Pro - Llama-3 8B (retires Jun 5)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nousresearch/hermes-3-llama-3.1-405b", name="Nous: Hermes 3 405B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nousresearch/hermes-3-llama-3.1-70b", name="Nous: Hermes 3 70B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nousresearch/hermes-4-405b", name="Nous: Hermes 4 405B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nousresearch/hermes-4-70b", name="Nous: Hermes 4 70B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/llama-3.1-nemotron-70b-instruct", name="Llama 3.1 Nemotron 70b Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/llama-3.1-nemotron-ultra-253b-v1", name="Llama-3.1-Nemotron-Ultra-253B-v1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/llama-3.3-nemotron-super-49b-v1.5", name="NVIDIA: Llama 3.3 Nemotron Super 49B V1.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-3-nano-30b-a3b", name="nemotron-3-nano-30b-a3b", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name="NVIDIA: Nemotron 3 Nano Omni (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-3-super-120b-a12b", name="Nemotron 3 Super", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-3-super-120b-a12b:free", name="NVIDIA: Nemotron 3 Super (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-nano-12b-v2-vl", name="NVIDIA: Nemotron Nano 12B 2 VL", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "nvidia/nemotron-nano-9b-v2", name="NVIDIA: Nemotron Nano 9B V2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-3.5-turbo", name="OpenAI: GPT-3.5 Turbo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-3.5-turbo-0613", name="OpenAI: GPT-3.5 Turbo (older v0613)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-3.5-turbo-16k", name="OpenAI: GPT-3.5 Turbo 16k", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-3.5-turbo-instruct", name="OpenAI: GPT-3.5 Turbo Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4", name="GPT-4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4-0314", name="OpenAI: GPT-4 (older v0314) ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4-1106-preview", name="OpenAI: GPT-4 Turbo (older v1106) ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4-turbo", name="GPT-4 Turbo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4-turbo-preview", name="OpenAI: GPT-4 Turbo Preview ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4.1", name="OpenAI: GPT-4.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4.1-mini", name="OpenAI: GPT-4.1 Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4.1-nano", name="OpenAI: GPT-4.1 Nano", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o", name="GPT-4o", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-2024-05-13", name="OpenAI: GPT-4o (2024-05-13)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-2024-08-06", name="OpenAI: GPT-4o (2024-08-06)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-2024-11-20", name="OpenAI: GPT-4o (2024-11-20)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-audio-preview", name="OpenAI: GPT-4o Audio", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-mini", name="GPT-4o mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-mini-2024-07-18", name="OpenAI: GPT-4o-mini (2024-07-18)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-mini-search-preview", name="OpenAI: GPT-4o-mini Search Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o-search-preview", name="OpenAI: GPT-4o Search Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-4o:extended", name="OpenAI: GPT-4o (extended)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5", name="GPT-5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-chat", name="OpenAI: GPT-5 Chat", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-codex", name="GPT-5 Codex", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-image", name="OpenAI: GPT-5 Image ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-image-mini", name="OpenAI: GPT-5 Image Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-mini", name="OpenAI: GPT-5 Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-nano", name="OpenAI: GPT-5 Nano", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5-pro", name="OpenAI: GPT-5 Pro ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.1", name="GPT-5.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.1-chat", name="GPT-5.1 Chat", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.1-codex", name="GPT-5.1 Codex", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.1-codex-max", name="OpenAI: GPT-5.1-Codex-Max", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.1-codex-mini", name="GPT-5.1-Codex-Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.2", name="GPT-5.2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.2-chat", name="OpenAI: GPT-5.2 Chat (retires Aug 10)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.2-codex", name="GPT-5.2 Codex", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.2-pro", name="GPT-5.2-Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.3-chat", name="GPT-5.3 Chat", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.3-codex", name="GPT-5.3 Codex", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.4", name="GPT-5.4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.4-image-2", name="OpenAI: GPT-5.4 Image 2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.4-mini", name="GPT-5.4 Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.4-nano", name="GPT-5.4 Nano", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.4-pro", name="GPT-5.4 Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.5", name="GPT-5.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-5.5-pro", name="GPT-5.5 Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-audio", name="OpenAI: GPT Audio", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-audio-mini", name="OpenAI: GPT Audio Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-chat-latest", name="OpenAI: GPT Chat Latest", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-oss-120b", name="GPT OSS 120B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-oss-120b:exacto", name="OpenAI: gpt-oss-120b (exacto)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-oss-20b", name="GPT OSS 20B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/gpt-oss-safeguard-20b", name="Safety GPT OSS 20B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o1", name="o1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o1-pro", name="OpenAI: o1-pro ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o3", name="o3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o3-deep-research", name="OpenAI: o3 Deep Research ($$$$)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o3-mini", name="o3-mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o3-mini-high", name="OpenAI: o3 Mini High", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o3-pro", name="o3-pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o4-mini", name="o4-mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o4-mini-deep-research", name="OpenAI: o4 Mini Deep Research", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openai/o4-mini-high", name="OpenAI: o4 Mini High", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "opengvlab/internvl3-78b", name="OpenGVLab: InternVL3 78B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/auto", name="Auto Router", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/bodybuilder", name="Body Builder (beta)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/elephant-alpha", name="Elephant (new)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/free", name="Free Models Router", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/healer-alpha", name="Healer Alpha", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/hunter-alpha", name="Hunter Alpha", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/owl-alpha", name="Owl Alpha", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "openrouter/pareto-code", name="Pareto Code Router", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perceptron/perceptron-mk1", name="Perceptron: Perceptron Mk1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perplexity/sonar", name="Perplexity: Sonar", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perplexity/sonar-deep-research", name="Perplexity: Sonar Deep Research", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perplexity/sonar-pro", name="Perplexity: Sonar Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perplexity/sonar-pro-search", name="Perplexity: Sonar Pro Search", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "perplexity/sonar-reasoning-pro", name="Perplexity: Sonar Reasoning Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "poolside/laguna-m.1:free", name="Poolside: Laguna M.1 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "poolside/laguna-xs.2:free", name="Poolside: Laguna XS.2 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "prime-intellect/intellect-3", name="Prime Intellect: INTELLECT-3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-2.5-72b-instruct", name="Qwen2.5 72B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-2.5-7b-instruct", name="Qwen: Qwen2.5 7B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-2.5-coder-32b-instruct", name="Qwen2.5 Coder 32B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-2.5-vl-7b-instruct", name="Qwen: Qwen2.5-VL 7B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-max", name="Qwen: Qwen-Max", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-plus", name="Qwen: Qwen-Plus", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-plus-2025-07-28", name="Qwen: Qwen Plus 0728", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-plus-2025-07-28:thinking", name="Qwen: Qwen Plus 0728 (thinking)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-turbo", name="Qwen: Qwen-Turbo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-vl-max", name="Qwen: Qwen VL Max", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen-vl-plus", name="Qwen: Qwen VL Plus", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen2.5-coder-7b-instruct", name="Qwen2.5 Coder 7b Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen2.5-vl-32b-instruct", name="Qwen: Qwen2.5 VL 32B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen2.5-vl-72b-instruct", name="Qwen: Qwen2.5 VL 72B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-14b", name="Qwen: Qwen3 14B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-235b-a22b", name="Qwen: Qwen3 235B A22B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-235b-a22b-2507", name="Qwen: Qwen3 235B A22B Instruct 2507", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-235b-a22b-thinking-2507", name="Qwen: Qwen3 235B A22B Thinking 2507", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-30b-a3b", name="Qwen: Qwen3 30B A3B (retires Jun 5)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-30b-a3b-instruct-2507", name="Qwen: Qwen3 30B A3B Instruct 2507", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-30b-a3b-thinking-2507", name="Qwen: Qwen3 30B A3B Thinking 2507", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-32b", name="Qwen3 32B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-8b", name="Qwen: Qwen3 8B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder", name="Qwen: Qwen3 Coder 480B A35B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder-30b-a3b-instruct", name="Qwen: Qwen3 Coder 30B A3B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder-flash", name="Qwen: Qwen3 Coder Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder-next", name="Qwen: Qwen3 Coder Next", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder-plus", name="Qwen3-Coder-Plus", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-coder:exacto", name="Qwen: Qwen3 Coder 480B A35B (exacto)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-max", name="Qwen3-Max-Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-max-thinking", name="Qwen: Qwen3 Max Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-next-80b-a3b-instruct", name="Qwen3-Next-80B-A3B-Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-next-80b-a3b-thinking", name="Qwen3-Next-80B-A3B-Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-235b-a22b-instruct", name="Qwen: Qwen3 VL 235B A22B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-235b-a22b-thinking", name="Qwen: Qwen3 VL 235B A22B Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-30b-a3b-instruct", name="Qwen: Qwen3 VL 30B A3B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-30b-a3b-thinking", name="Qwen: Qwen3 VL 30B A3B Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-32b-instruct", name="Qwen: Qwen3 VL 32B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-8b-instruct", name="Qwen: Qwen3 VL 8B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3-vl-8b-thinking", name="Qwen: Qwen3 VL 8B Thinking", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-122b-a10b", name="Qwen3.5 122B-A10B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-27b", name="Qwen: Qwen3.5-27B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-35b-a3b", name="Qwen: Qwen3.5-35B-A3B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-397b-a17b", name="Qwen3.5-397B-A17B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-9b", name="Qwen: Qwen3.5-9B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-flash-02-23", name="Qwen: Qwen3.5-Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-plus-02-15", name="Qwen: Qwen3.5 Plus 2026-02-15", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.5-plus-20260420", name="Qwen: Qwen3.5 Plus 2026-04-20", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-27b", name="Qwen: Qwen3.6 27B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-35b-a3b", name="Qwen: Qwen3.6 35B A3B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-flash", name="Qwen: Qwen3.6 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-max-preview", name="Qwen: Qwen3.6 Max Preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-plus", name="Qwen3.6-Plus", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-plus-preview:free", name="Qwen: Qwen3.6 Plus Preview (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.6-plus:free", name="Qwen: Qwen3.6 Plus (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwen3.7-max", name="Qwen: Qwen3.7 Max", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "qwen/qwq-32b", name="Qwen: QwQ 32B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "raifle/sorcererlm-8x22b", name="SorcererLM 8x22B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "reka/reka-edge", name="Reka Edge", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "rekaai/reka-edge", name="Reka Edge", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "rekaai/reka-flash-3", name="Reka Flash 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "relace/relace-apply-3", name="Relace: Relace Apply 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "relace/relace-search", name="Relace: Relace Search", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "sao10k/l3-euryale-70b", name="Sao10k: Llama 3 Euryale 70B v2.1 (retires Jun 5)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "sao10k/l3-lunaris-8b", name="Sao10K: Llama 3 8B Lunaris", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "sao10k/l3.1-70b-hanami-x1", name="Sao10K: Llama 3.1 70B Hanami x1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "sao10k/l3.1-euryale-70b", name="Sao10K: Llama 3.1 Euryale 70B v2.2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "sao10k/l3.3-euryale-70b", name="Sao10K: Llama 3.3 Euryale 70B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stealth/claude-opus-4.6", name="Stealth: Claude Opus 4.6 (20% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stealth/claude-opus-4.7", name="Stealth: Claude Opus 4.7 (20% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stealth/claude-opus-4.8", name="Stealth: Claude Opus 4.8 (20% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stealth/claude-sonnet-4.6", name="Stealth: Claude Sonnet 4.6 (20% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stealth/qwen3.6-plus", name="Stealth: Qwen3.6 Plus (50% off)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stepfun/step-3.5-flash", name="Step 3.5 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stepfun/step-3.5-flash:free", name="StepFun: Step 3.5 Flash (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stepfun/step-3.7-flash", name="StepFun: Step 3.7 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "stepfun/step-3.7-flash:free", name="StepFun: Step 3.7 Flash (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "switchpoint/router", name="Switchpoint Router", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "tencent/hunyuan-a13b-instruct", name="Tencent: Hunyuan A13B Instruct", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "tencent/hy3-preview", name="Hy3 preview", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "tencent/hy3-preview:free", name="Tencent: Hy3 preview (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "tencent/hy3:free", name="Tencent: Hy3 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "thedrummer/cydonia-24b-v4.1", name="TheDrummer: Cydonia 24B V4.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "thedrummer/rocinante-12b", name="TheDrummer: Rocinante 12B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "thedrummer/skyfall-36b-v2", name="TheDrummer: Skyfall 36B V2", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "thedrummer/unslopnemo-12b", name="TheDrummer: UnslopNemo 12B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "tngtech/deepseek-r1t2-chimera", name="TNG: DeepSeek R1T2 Chimera", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "undi95/remm-slerp-l2-13b", name="ReMM SLERP 13B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "upstage/solar-pro-3", name="Upstage: Solar Pro 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "writer/palmyra-x5", name="Writer: Palmyra X5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-3", name="xAI: Grok 3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-3-beta", name="xAI: Grok 3 Beta", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-3-mini", name="xAI: Grok 3 Mini", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-3-mini-beta", name="xAI: Grok 3 Mini Beta", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4", name="Grok 4", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4-fast", name="Grok 4 Fast", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.1-fast", name="Grok 4.1 Fast", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.20", name="xAI: Grok 4.20", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.20-beta", name="xAI: Grok 4.20 Beta", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.20-multi-agent", name="xAI: Grok 4.20 Multi-Agent", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.20-multi-agent-beta", name="xAI: Grok 4.20 Multi-Agent Beta", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-4.3", name="xAI: Grok 4.3", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-build-0.1", name="xAI: Grok Build 0.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-code-fast-1", name="Grok Code Fast 1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "x-ai/grok-code-fast-1:optimized:free", name="xAI: Grok Code Fast 1, retiring May 15 (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2-flash", name="MiMo-V2-Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2-omni", name="MiMo V2 Omni", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2-omni:free", name="Xiaomi: MiMo-V2-Omni (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2-pro", name="MiMo V2 Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2-pro:free", name="Xiaomi: MiMo-V2-Pro (free)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2.5", name="MiMo-V2.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "xiaomi/mimo-v2.5-pro", name="MiMo-V2.5-Pro", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4-32b", name="Z.ai: GLM 4 32B", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.5", name="GLM 4.5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.5-air", name="GLM 4.5 Air", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.5v", name="Z.ai: GLM 4.5V", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.6", name="GLM 4.6", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.6:exacto", name="Z.ai: GLM 4.6 (exacto)", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.6v", name="GLM 4.6V", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.7", name="GLM 4.7", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-4.7-flash", name="Z.ai: GLM 4.7 Flash", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-5", name="GLM 5", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-5-turbo", name="GLM 5 Turbo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-5.1", name="GLM-5.1", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
_add("kilo", "z-ai/glm-5v-turbo", name="GLM 5V Turbo", api="openai-completions", base_url="https://api.kilo.ai/api/gateway")
# opencode
_add("opencode", "glm-5-free", name="GLM-5 Free", api="openai-completions", base_url="https://opencode.ai/zen/v1")
_add("opencode", "gpt-5.3-codex-spark", name="GPT-5.3 Codex Spark", api="openai-responses", base_url="https://opencode.ai/zen/v1")
_add("opencode", "gpt-5.4", name="GPT-5.4", api="openai-responses", base_url="https://opencode.ai/zen/v1")
_add("opencode", "gpt-5.4-pro", name="GPT-5.4 Pro", api="openai-responses", base_url="https://opencode.ai/zen/v1")
_add("opencode", "kimi-k2.5-free", name="Kimi K2.5 Free", api="openai-completions", base_url="https://opencode.ai/zen/v1")
def get_model(provider: str, model: str): return PROVIDERS.get(provider, {}).get(model)
def get_provider_api(provider: str): p = PROVIDERS.get(provider); return list(p.values())[0].api if p else None
